create table if not exists public.contact_click_events (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  action text not null check (action in ('whatsapp', 'call')),
  source text not null check (source in ('directory_card', 'profile_header', 'profile_service')),
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists contact_click_events_profile_id_idx
  on public.contact_click_events (profile_id);

create index if not exists contact_click_events_created_at_idx
  on public.contact_click_events (created_at desc);

create index if not exists contact_click_events_action_idx
  on public.contact_click_events (action);

alter table public.contact_click_events enable row level security;
